### PR TITLE
Add support for latest version (9.16.1)

### PR DESCRIPTION
**Pull request by R0rt1z2**
Most of the features I've tested seem to be working as expected, but I might have missed something. If you (or anyone) notice(s) any issue(s), please let me know. Most of the changes were related to obfuscation, which (as expected) has changed over the latest Grindr releases. I also had to revert the casting method for messages since it was constantly crashing (and the [old method](https://github.com/ElJaviLuki/GrindrPlus/commit/76ea9bcf05416f5f82eee5db05ea287de663b59b#diff-9df8d9f89ece476cb0bf3793540e30c4e5159c71778f093af6e74207afb45dc0L600) seems to work just fine). I also bumped external versions just in case (not sure if this was required).

For testing purposes, I used the most recent version of the app available on [apkmirror.com](https://www.apkmirror.com/apk/grindr-llc/grindr-gay-chat-meet-date/), as mentioned in the `README.md`. If anyone is interested in trying it out, the updated GrindrPlus app can be downloaded [here](https://github.com/ElJaviLuki/GrindrPlus/files/12587355/app-debug.zip
) (extract the ZIP).

* _**sha256** (_APK_) - `16174df1d8094349e2a240be0d9b5d5ded96f971ba97f92d2c48b3a39d6ff0ba`)._

> _(Y por cierto, gracias por tu trabajo :D)_

### CODE REVIEW

**Comment by R0rt1z2** [comment]
Buggy, **DNM**.

**Comment by R0rt1z2** [comment]
https://github.com/RobbieTechie/GrindrPlus has less bugs and seems to work fine. Closing this PR.

**Comment by ElJaviLuki** [comment]
Sorry, just noticed about this pull request. Your fork looks promising, I'll play around with it for a bit to see what we can come up with. :p

**Comment by R0rt1z2** [comment]
> Sorry, just noticed about this pull request. Your fork looks promising, I'll play around with it for a bit to see what we can come up with. :p

No problem. In any case, the most important commit is https://github.com/R0rt1z2/G/commit/c210f4bd47054e9b3756af278872d361d4d76b97.

**Pull request closed without merging**
