### PR TITLE
Bump to 8.18.1

### PR DESCRIPTION
**Pull request by RobbieTechie**
Adjustments for 8.,18.1

### CODE REVIEW

**Review by Zarkoob — APPROVED** [review]
Works for me when I build it.

**Review by Zarkoob — APPROVED** [review]
Built with these changes on my machine and target device and as such app still runs correctly.

**Comment by mc90blue** [comment]
> Adjustments for 8.,18.1

Hi Robbie, could you release this apk?

**Comment by Zarkoob** [comment]
> > Adjustments for 8.,18.1
> 
> Hi Robbie, could you release this apk?

While we're at it maybe we can get a fix for 8.19 in the works? The changes are just a bit out of my league maybe @ElJaviLuki and @RobbieTechie could help us a tiny bit?

**Comment by RobbieTechie** [comment]
> > > Adjustments for 8.,18.1
> > 
> > 
> > Hi Robbie, could you release this apk?
> 
> While we're at it maybe we can get a fix for 8.19 in the works? The changes are just a bit out of my league maybe @ElJaviLuki and @RobbieTechie could help us a tiny bit?

For the online time indicator, based off 8.17.1 currently on here, you'd need to change line 110 in Obfuscation.kt `const val ProfileUtils = "$_utils.u0"` to `const val ProfileUtils = "$_utils.t0"` so simply change the "u" to a "t"

UnlimitedExpiringPhotos is the same

I'll edit this and add more info as I have it

**Comment by Zarkoob** [comment]
> > > > Adjustments for 8.,18.1
> > > 
> > > 
> > > Hi Robbie, could you release this apk?
> > 
> > 
> > While we're at it maybe we can get a fix for 8.19 in the works? The changes are just a bit out of my league maybe @ElJaviLuki and @RobbieTechie could help us a tiny bit?
> 
> For the online time indicator, based off 8.17.1 currently on here, you'd need to change line 110 in Obfuscation.kt `const val ProfileUtils = "$_utils.u0"` to `const val ProfileUtils = "$_utils.t0"` so simply change the "u" to a "t"
> 
> UnlimitedExpiringPhotos is the same
> 
> For the view, to get the extra profile fields to show up: in Obfuscation.kt under the view object on line 119, change
> 
> `const val ExtendedProfileFieldView = "$_view.d4"` to `const val ExtendedProfileFieldView = "$_view.k4"`
> 
> and also change the color for pure white symbol on line 74 from
> 
> const val grindr_pure_white = "M" to const val grindr_pure_white = "O"
> 
> the gold color remains the same. If pure_white is not changed the text will be black and will not show well with the gray background...
> 
> I'll edit this and add more info as I have it
> 
> They have added new features too that interfere with all the features being set to true, that seem to interfere when set to true
> 
> LegacyCascadeWithFreeFilters, UnifiedCascadeWithNoFreeFilters, UnifiedCascadeWithFreeFilters;

Ok how do you know how to find the links to the file? Do you use mtimproxy or Charles?

**Pull request closed without merging**
