### PR TITLE
Bump to 8.20.0

### PR DESCRIPTION
**Pull request by RobbieTechie**
Adjustments for 8.20.0
19-10-2022

### CODE REVIEW

**Comment by Zarkoob** [comment]
Sweet.. building now to test!   I need to learn how to find these obfuscation changes haha

**Comment by RobbieTechie** [comment]
> Sweet.. building now to test! I need to learn how to find these obfuscation changes haha
> 
> edit: ummm playstore doesn't have 8.20.0 ... yet?


They seem to update in differant regions at different times, you can get it off APKMirror:

https://www.apkmirror.com/apk/grindr-llc/grindr-gay-chat-meet-date/grindr-gay-chat-meet-date-8-20-0-release/

**Comment by secrj** [comment]
It seems that works with the 8.20 but makes the filters go on the left of the app (still not working) and also the fresh doesn't work either

**Comment by RobbieTechie** [comment]
> It seems that works with the 8.20 but makes the filters go on the left of the app (still not working) and also the fresh doesn't work either

If you mean all the filters, they are checked server side now which you'd know if you read through the closed issues.

As for the fresh grid, I have had no problems with it and there have been no other issues raised by others regarding it.  Perhaps they were playing with their server code, and I do mean playing given that they seem rather clueless these days...

The interface was recently changed and they had some code issues with it, They were  testing it quite a bit with 8.19 and experimenting with it and seem to be working out bugs to keep it this way, which is why the filters are now above the grid towards the left side.

**Pull request closed without merging**
